repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.90.6
    hooks:
      - id: trufflehog
        name: TruffleHog (verified results)
        args:
          # Only verified results, fail on findings; fast incremental scan
          - --results=verified
          - --fail
