# Configuration for cargo-deny
# https://github.com/EmbarkStudios/cargo-deny

[advisories]
# Deny known security vulnerabilities
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

copyleft = "warn"
unlicensed = "deny"
default = "deny"

[[licenses.exceptions]]
# Ring uses a custom license but is widely trusted
name = "ring"
allow = ["ISC", "MIT", "OpenSSL"]

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# Skip certain crates that commonly have multiple versions
skip = [
    { name = "windows-sys" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_msvc" },
]

[sources]
# Deny crates from unknown registries
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]