# Configuration for release-plz
# https://release-plz.ieni.dev/docs/config

[workspace]
# Enable changelog generation
changelog_update = true

# Enable git releases and tags
git_release_enable = true
git_tag_enable = true

# PR settings
pr_labels = ["release"]
pr_draft = false
pr_name = "chore: release version {{version}}"

# Publishing
publish = true

# GitHub release body template
git_release_body = """
## What's Changed

{%- if changelog %}
{{ changelog }}
{%- else %}
_No changelog available_
{%- endif %}

**Full Changelog**: https://github.com/{{ repository_url }}/compare/v{{ previous_version }}...v{{ version }}
"""

# PR body template  
pr_body = """
{%- for package in packages -%}
{%- if package.version_update -%}
## 📦 {{ package.name }} {{ package.version_update.prev_version }} → {{ package.version_update.version }}

{%- if package.changelog %}

### Changelog

{{ package.changelog }}
{%- else %}

_No changelog available for this release_
{%- endif %}

{%- endif %}
{%- endfor %}

---
_This PR was generated by [release-plz](https://github.com/MarcoIeni/release-plz/)_
"""