# Configuration for release-plz
# https://release-plz.ieni.dev/docs/config

[workspace]
# Disable changelog generation for generated code
changelog_update = false

# Enable git releases and tags
git_release_enable = true
git_tag_enable = true

# PR settings
pr_labels = ["release"]
pr_draft = false
pr_name = "chore: release version {{version}}"

# Publishing
publish = true