/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`scores_v3_get_many_v3`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScoresV3GetManyV3Error {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    UnknownValue(serde_json::Value),
}

/// Get a list of scores with a polymorphic `value` field (v3).  The `value` field type depends on `dataType`: - `NUMERIC` → number - `BOOLEAN` → boolean - `CATEGORICAL`, `TEXT`, `CORRECTION` → string  The response always includes the core fields: id, projectId, name, value, dataType, source, timestamp, environment, createdAt, updatedAt.  Additional field groups can be requested via the `fields` parameter: - `details` — adds comment, configId, metadata - `subject` — adds the subject object describing the entity the score   is attached to: kind (trace, observation, session, or experiment),   id, and traceId for observation-level scores - `annotation` — adds authorUserId, queueId  Unknown group names return HTTP 400.
#[bon::builder]
pub async fn scores_v3_get_many_v3(
    configuration: &configuration::Configuration,
    limit: Option<i32>,
    cursor: Option<&str>,
    fields: Option<&str>,
    id: Option<&str>,
    name: Option<&str>,
    source: Option<&str>,
    data_type: Option<&str>,
    environment: Option<&str>,
    config_id: Option<&str>,
    queue_id: Option<&str>,
    author_user_id: Option<&str>,
    value: Option<&str>,
    value_min: Option<f64>,
    value_max: Option<f64>,
    trace_id: Option<&str>,
    session_id: Option<&str>,
    observation_id: Option<&str>,
    experiment_id: Option<&str>,
    from_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    to_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
) -> Result<models::GetScoresV3Response, Error<ScoresV3GetManyV3Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_query_cursor = cursor;
    let p_query_fields = fields;
    let p_query_id = id;
    let p_query_name = name;
    let p_query_source = source;
    let p_query_data_type = data_type;
    let p_query_environment = environment;
    let p_query_config_id = config_id;
    let p_query_queue_id = queue_id;
    let p_query_author_user_id = author_user_id;
    let p_query_value = value;
    let p_query_value_min = value_min;
    let p_query_value_max = value_max;
    let p_query_trace_id = trace_id;
    let p_query_session_id = session_id;
    let p_query_observation_id = observation_id;
    let p_query_experiment_id = experiment_id;
    let p_query_from_timestamp = from_timestamp;
    let p_query_to_timestamp = to_timestamp;

    let uri_str = format!("{}/api/public/v3/scores", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_source {
        req_builder = req_builder.query(&[("source", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_data_type {
        req_builder = req_builder.query(&[("dataType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_environment {
        req_builder = req_builder.query(&[("environment", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_config_id {
        req_builder = req_builder.query(&[("configId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_queue_id {
        req_builder = req_builder.query(&[("queueId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_author_user_id {
        req_builder = req_builder.query(&[("authorUserId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_value {
        req_builder = req_builder.query(&[("value", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_value_min {
        req_builder = req_builder.query(&[("valueMin", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_value_max {
        req_builder = req_builder.query(&[("valueMax", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_trace_id {
        req_builder = req_builder.query(&[("traceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_session_id {
        req_builder = req_builder.query(&[("sessionId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_observation_id {
        req_builder = req_builder.query(&[("observationId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_experiment_id {
        req_builder = req_builder.query(&[("experimentId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from_timestamp {
        req_builder = req_builder.query(&[("fromTimestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to_timestamp {
        req_builder = req_builder.query(&[("toTimestamp", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetScoresV3Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetScoresV3Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScoresV3GetManyV3Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
