/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`unstable_dashboards_add_placement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsAddPlacementError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status409(models::UnstablePublicApiError),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_create`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsCreateError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsDeleteError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_delete_placement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsDeletePlacementError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsGetError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsListError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsUpdateError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unstable_dashboards_update_placement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardsUpdatePlacementError {
    Status400(serde_json::Value),
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status404(serde_json::Value),
    Status405(serde_json::Value),
    Status429(models::UnstablePublicApiError),
    Status500(models::UnstablePublicApiError),
    UnknownValue(serde_json::Value),
}

/// Add a placement to a dashboard grid (see `DashboardPlacement` for grid semantics).  `id` and the position fields are optional: when omitted, the placement gets a server-generated id and is appended below all existing tiles as a 6x6 tile. Returns the created placement.  The referenced widget must exist in the same project or be a Langfuse-managed widget. The API returns `409` if a placement with the same `id` already exists on the dashboard.
#[bon::builder]
pub async fn unstable_dashboards_add_placement(
    configuration: &configuration::Configuration,
    dashboard_id: &str,
    unstable_create_dashboard_placement_request: models::UnstableCreateDashboardPlacementRequest,
) -> Result<models::UnstableDashboardPlacement, Error<UnstableDashboardsAddPlacementError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_dashboard_id = dashboard_id;
    let p_body_unstable_create_dashboard_placement_request =
        unstable_create_dashboard_placement_request;

    let uri_str = format!(
        "{}/api/public/unstable/dashboards/{dashboardId}/placements",
        configuration.base_path,
        dashboardId = crate::apis::urlencode(p_path_dashboard_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_unstable_create_dashboard_placement_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDashboardPlacement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDashboardPlacement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsAddPlacementError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Create a dashboard.
#[bon::builder]
pub async fn unstable_dashboards_create(
    configuration: &configuration::Configuration,
    unstable_create_dashboard_request: models::UnstableCreateDashboardRequest,
) -> Result<models::UnstableDashboard, Error<UnstableDashboardsCreateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_unstable_create_dashboard_request = unstable_create_dashboard_request;

    let uri_str = format!("{}/api/public/unstable/dashboards", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_unstable_create_dashboard_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDashboard`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDashboard`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsCreateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete a dashboard.
#[bon::builder]
pub async fn unstable_dashboards_delete(
    configuration: &configuration::Configuration,
    dashboard_id: &str,
) -> Result<models::UnstableDeleteDashboardResponse, Error<UnstableDashboardsDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_dashboard_id = dashboard_id;

    let uri_str = format!(
        "{}/api/public/unstable/dashboards/{dashboardId}",
        configuration.base_path,
        dashboardId = crate::apis::urlencode(p_path_dashboard_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDeleteDashboardResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDeleteDashboardResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Remove a placement from a dashboard grid without deleting the referenced widget.
#[bon::builder]
pub async fn unstable_dashboards_delete_placement(
    configuration: &configuration::Configuration,
    dashboard_id: &str,
    placement_id: &str,
) -> Result<
    models::UnstableDeleteDashboardPlacementResponse,
    Error<UnstableDashboardsDeletePlacementError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_dashboard_id = dashboard_id;
    let p_path_placement_id = placement_id;

    let uri_str = format!(
        "{}/api/public/unstable/dashboards/{dashboardId}/placements/{placementId}",
        configuration.base_path,
        dashboardId = crate::apis::urlencode(p_path_dashboard_id),
        placementId = crate::apis::urlencode(p_path_placement_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDeleteDashboardPlacementResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDeleteDashboardPlacementResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsDeletePlacementError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a dashboard by id.
#[bon::builder]
pub async fn unstable_dashboards_get(
    configuration: &configuration::Configuration,
    dashboard_id: &str,
) -> Result<models::UnstableDashboard, Error<UnstableDashboardsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_dashboard_id = dashboard_id;

    let uri_str = format!(
        "{}/api/public/unstable/dashboards/{dashboardId}",
        configuration.base_path,
        dashboardId = crate::apis::urlencode(p_path_dashboard_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDashboard`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDashboard`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List dashboards in the project, ordered by most recently updated first.
#[bon::builder]
pub async fn unstable_dashboards_list(
    configuration: &configuration::Configuration,
    page: Option<i32>,
    limit: Option<i32>,
) -> Result<models::UnstableDashboardList, Error<UnstableDashboardsListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_limit = limit;

    let uri_str = format!("{}/api/public/unstable/dashboards", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDashboardList`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDashboardList`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update a dashboard's name, description, definition, or filters.
#[bon::builder]
pub async fn unstable_dashboards_update(
    configuration: &configuration::Configuration,
    dashboard_id: &str,
    unstable_update_dashboard_request: models::UnstableUpdateDashboardRequest,
) -> Result<models::UnstableDashboard, Error<UnstableDashboardsUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_dashboard_id = dashboard_id;
    let p_body_unstable_update_dashboard_request = unstable_update_dashboard_request;

    let uri_str = format!(
        "{}/api/public/unstable/dashboards/{dashboardId}",
        configuration.base_path,
        dashboardId = crate::apis::urlencode(p_path_dashboard_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_unstable_update_dashboard_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDashboard`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDashboard`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Move or resize a placement. All fields are optional; at least one is required. Omitted fields keep their current value. The placement's content (widget/preset reference) and id cannot change — delete and re-add the placement to swap content. Returns the updated placement.
#[bon::builder]
pub async fn unstable_dashboards_update_placement(
    configuration: &configuration::Configuration,
    dashboard_id: &str,
    placement_id: &str,
    unstable_update_dashboard_placement_request: models::UnstableUpdateDashboardPlacementRequest,
) -> Result<models::UnstableDashboardPlacement, Error<UnstableDashboardsUpdatePlacementError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_dashboard_id = dashboard_id;
    let p_path_placement_id = placement_id;
    let p_body_unstable_update_dashboard_placement_request =
        unstable_update_dashboard_placement_request;

    let uri_str = format!(
        "{}/api/public/unstable/dashboards/{dashboardId}/placements/{placementId}",
        configuration.base_path,
        dashboardId = crate::apis::urlencode(p_path_dashboard_id),
        placementId = crate::apis::urlencode(p_path_placement_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_unstable_update_dashboard_placement_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnstableDashboardPlacement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnstableDashboardPlacement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnstableDashboardsUpdatePlacementError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
