/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BlobStorageIntegrationType {
    #[serde(rename = "S3")]
    S3,
    #[serde(rename = "S3_COMPATIBLE")]
    S3Compatible,
    #[serde(rename = "AZURE_BLOB_STORAGE")]
    AzureBlobStorage,
}

impl std::fmt::Display for BlobStorageIntegrationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::S3 => write!(f, "S3"),
            Self::S3Compatible => write!(f, "S3_COMPATIBLE"),
            Self::AzureBlobStorage => write!(f, "AZURE_BLOB_STORAGE"),
        }
    }
}

impl Default for BlobStorageIntegrationType {
    fn default() -> BlobStorageIntegrationType {
        Self::S3
    }
}
