/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BlobStorageExportMode {
    #[serde(rename = "FULL_HISTORY")]
    FullHistory,
    #[serde(rename = "FROM_TODAY")]
    FromToday,
    #[serde(rename = "FROM_CUSTOM_DATE")]
    FromCustomDate,
}

impl std::fmt::Display for BlobStorageExportMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FullHistory => write!(f, "FULL_HISTORY"),
            Self::FromToday => write!(f, "FROM_TODAY"),
            Self::FromCustomDate => write!(f, "FROM_CUSTOM_DATE"),
        }
    }
}

impl Default for BlobStorageExportMode {
    fn default() -> BlobStorageExportMode {
        Self::FullHistory
    }
}
