/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatMessageWithPlaceholders {
    ChatMessage(Box<models::ChatMessage>),
    PlaceholderMessage(Box<models::PlaceholderMessage>),
}

impl Default for ChatMessageWithPlaceholders {
    fn default() -> Self {
        Self::ChatMessage(Default::default())
    }
}
