/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Creator : User who created the resource, or `null` when no user can be resolved.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Creator {
    /// User identifier.
    #[serde(rename = "id")]
    pub id: String,
    /// User name, or `null` when unavailable.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
}

impl Creator {
    /// User who created the resource, or `null` when no user can be resolved.
    pub fn new(id: String, name: Option<String>) -> Creator {
        Creator { id, name }
    }
}
