/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct CreateCodeEvaluatorRequest1 {
    /// Human-readable evaluator name. Names are not identifiers and do not need to be unique.
    #[serde(rename = "name")]
    pub name: String,
    /// Optional human-readable evaluator description.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Source code executed for each matched observation.
    #[serde(rename = "sourceCode")]
    pub source_code: String,
    #[serde(rename = "sourceCodeLanguage")]
    pub source_code_language: models::CodeEvaluatorSourceCodeLanguage,
}

impl CreateCodeEvaluatorRequest1 {
    pub fn new(
        name: String,
        r#type: Type,
        source_code: String,
        source_code_language: models::CodeEvaluatorSourceCodeLanguage,
    ) -> CreateCodeEvaluatorRequest1 {
        CreateCodeEvaluatorRequest1 {
            name,
            description: None,
            r#type,
            source_code,
            source_code_language,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "code")]
    Code,
}

impl Default for Type {
    fn default() -> Type {
        Self::Code
    }
}
