/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateEvaluatorRequest : Initial evaluator definition with metadata and definition fields at the same level. The returned evaluator starts at version `1`.
/// Initial evaluator definition with metadata and definition fields at the same level. The returned evaluator starts at version `1`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEvaluatorRequest {
    CreateLlmAsJudgeEvaluatorRequest1(Box<models::CreateLlmAsJudgeEvaluatorRequest1>),
    CreateCodeEvaluatorRequest1(Box<models::CreateCodeEvaluatorRequest1>),
}

impl Default for CreateEvaluatorRequest {
    fn default() -> Self {
        Self::CreateLlmAsJudgeEvaluatorRequest1(Default::default())
    }
}
