/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Deprecation : Migration signal returned by deprecated endpoints. Optional fields are omitted when they have no value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Deprecation {
    /// Human- and agent-readable summary of the deprecation and its replacement.
    #[serde(rename = "message")]
    pub message: String,
    /// The replacement endpoint, e.g. \"GET /api/public/v2/observations\". Omitted when the endpoint is being removed without a direct replacement.
    #[serde(
        rename = "replacement",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub replacement: Option<Option<String>>,
    /// Link to the migration documentation (markdown), when available.
    #[serde(
        rename = "docsUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub docs_url: Option<Option<String>>,
    /// ISO date after which the endpoint may stop working, when a removal date is committed.
    #[serde(
        rename = "sunsetAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sunset_at: Option<Option<String>>,
}

impl Deprecation {
    /// Migration signal returned by deprecated endpoints. Optional fields are omitted when they have no value.
    pub fn new(message: String) -> Deprecation {
        Deprecation {
            message,
            replacement: None,
            docs_url: None,
            sunset_at: None,
        }
    }
}
