/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvaluatorOutputScoreType : Structured score type returned by an evaluator.  This controls the type of score value Langfuse stores for evaluation results: - `NUMERIC`: a numeric score such as `0.82` - `BOOLEAN`: a boolean score such as `true` - `CATEGORICAL`: one or more category labels from a fixed list
/// Structured score type returned by an evaluator.  This controls the type of score value Langfuse stores for evaluation results: - `NUMERIC`: a numeric score such as `0.82` - `BOOLEAN`: a boolean score such as `true` - `CATEGORICAL`: one or more category labels from a fixed list
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EvaluatorOutputScoreType {
    #[serde(rename = "NUMERIC")]
    Numeric,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "CATEGORICAL")]
    Categorical,
}

impl std::fmt::Display for EvaluatorOutputScoreType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Numeric => write!(f, "NUMERIC"),
            Self::Boolean => write!(f, "BOOLEAN"),
            Self::Categorical => write!(f, "CATEGORICAL"),
        }
    }
}

impl Default for EvaluatorOutputScoreType {
    fn default() -> EvaluatorOutputScoreType {
        Self::Numeric
    }
}
