/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct EvaluatorVersionBase {
    /// Stable identifier of this evaluator version.
    #[serde(rename = "id")]
    pub id: String,
    /// Monotonically increasing evaluator version number.
    #[serde(rename = "version")]
    pub version: i32,
    /// Timestamp when this evaluator version was created.
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "createdBy")]
    pub created_by: Box<models::Creator>,
}

impl EvaluatorVersionBase {
    pub fn new(
        id: String,
        version: i32,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        created_by: models::Creator,
    ) -> EvaluatorVersionBase {
        EvaluatorVersionBase {
            id,
            version,
            created_at,
            created_by: Box::new(created_by),
        }
    }
}
