/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EvaluatorVersion {
    LlmAsJudgeEvaluatorVersion1(Box<models::LlmAsJudgeEvaluatorVersion1>),
    CodeEvaluatorVersion1(Box<models::CodeEvaluatorVersion1>),
}

impl Default for EvaluatorVersion {
    fn default() -> Self {
        Self::LlmAsJudgeEvaluatorVersion1(Default::default())
    }
}
