/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvaluatorOutputDefinition : Flat structured output definition used when creating or updating an evaluator.  - `dataType` is required. - `scoreReasoningInstructions` and `scoreValueInstructions` are optional instructions. - `minValue` and `maxValue` apply only to `NUMERIC` outputs. If both are set, `minValue` must not exceed `maxValue`. - `categories` and `shouldAllowMultipleMatches` apply only to `CATEGORICAL` outputs. - Do not send `version`; that is an internal storage detail.
/// Flat structured output definition used when creating or updating an evaluator.  - `dataType` is required. - `scoreReasoningInstructions` and `scoreValueInstructions` are optional instructions. - `minValue` and `maxValue` apply only to `NUMERIC` outputs. If both are set, `minValue` must not exceed `maxValue`. - `categories` and `shouldAllowMultipleMatches` apply only to `CATEGORICAL` outputs. - Do not send `version`; that is an internal storage detail.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EvaluatorOutputDefinition {
    PublicEvaluatorNumericScore1(Box<models::PublicEvaluatorNumericScore1>),
    PublicEvaluatorBooleanScore1(Box<models::PublicEvaluatorBooleanScore1>),
    PublicEvaluatorCategoricalScore1(Box<models::PublicEvaluatorCategoricalScore1>),
}

impl Default for EvaluatorOutputDefinition {
    fn default() -> Self {
        Self::PublicEvaluatorNumericScore1(Default::default())
    }
}
