/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Evaluator : One evaluator that can be used for scoring.  An evaluator describes **how** to score data. Associated evaluation rules describe **which** live objects should be evaluated.
/// One evaluator that can be used for scoring.  An evaluator describes **how** to score data. Associated evaluation rules describe **which** live objects should be evaluated.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Evaluator {
    LlmAsJudgeEvaluator1(Box<models::LlmAsJudgeEvaluator1>),
    CodeEvaluator1(Box<models::CodeEvaluator1>),
}

impl Default for Evaluator {
    fn default() -> Self {
        Self::LlmAsJudgeEvaluator1(Default::default())
    }
}
