/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvaluatorModelConfig : Explicit model configuration for an evaluator.  If the complete `modelConfig` is `null`, Langfuse uses the project's default evaluation model. If provided, the model must be available to the project when the evaluator or evaluation rule is enabled.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct EvaluatorModelConfig {
    /// Provider identifier, for example `openai` or `anthropic`.  To discover valid values for the current project, call `GET /api/public/llm-connections` and use one of the returned `provider` values.
    #[serde(rename = "provider")]
    pub provider: String,
    /// Model identifier exposed by the provider, for example `gpt-4.1-mini`.
    #[serde(rename = "model")]
    pub model: String,
}

impl EvaluatorModelConfig {
    /// Explicit model configuration for an evaluator.  If the complete `modelConfig` is `null`, Langfuse uses the project's default evaluation model. If provided, the model must be available to the project when the evaluator or evaluation rule is enabled.
    pub fn new(provider: String, model: String) -> EvaluatorModelConfig {
        EvaluatorModelConfig { provider, model }
    }
}
