/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct EvaluatorOutputDefinitionBase {
    /// Optional instructions for deriving the reasoning returned with the score.
    #[serde(
        rename = "scoreReasoningInstructions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub score_reasoning_instructions: Option<Option<String>>,
    /// Optional instructions for deriving the score value.
    #[serde(
        rename = "scoreValueInstructions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub score_value_instructions: Option<Option<String>>,
}

impl EvaluatorOutputDefinitionBase {
    pub fn new() -> EvaluatorOutputDefinitionBase {
        EvaluatorOutputDefinitionBase {
            score_reasoning_instructions: None,
            score_value_instructions: None,
        }
    }
}
