/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvaluatorChatMessage : One chat message in an evaluator prompt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct EvaluatorChatMessage {
    #[serde(rename = "role")]
    pub role: models::EvaluatorChatMessageRole,
    /// Message content. Evaluator variables use `{{variable}}` syntax.
    #[serde(rename = "content")]
    pub content: String,
}

impl EvaluatorChatMessage {
    /// One chat message in an evaluator prompt.
    pub fn new(role: models::EvaluatorChatMessageRole, content: String) -> EvaluatorChatMessage {
        EvaluatorChatMessage { role, content }
    }
}
