/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeedbackTargetType {
    #[serde(rename = "skill")]
    Skill,
    #[serde(rename = "mcp-tool")]
    McpTool,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "docs")]
    Docs,
    #[serde(rename = "public-api")]
    PublicApi,
    #[serde(rename = "other")]
    Other,
}

impl std::fmt::Display for FeedbackTargetType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Skill => write!(f, "skill"),
            Self::McpTool => write!(f, "mcp-tool"),
            Self::Cli => write!(f, "cli"),
            Self::Docs => write!(f, "docs"),
            Self::PublicApi => write!(f, "public-api"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for FeedbackTargetType {
    fn default() -> FeedbackTargetType {
        Self::Skill
    }
}
