/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct GetScoresV3Response {
    #[serde(rename = "data")]
    pub data: Vec<models::ScoreV3>,
    #[serde(rename = "meta")]
    pub meta: Box<models::GetScoresV3Meta>,
}

impl GetScoresV3Response {
    pub fn new(data: Vec<models::ScoreV3>, meta: models::GetScoresV3Meta) -> GetScoresV3Response {
        GetScoresV3Response {
            data,
            meta: Box::new(meta),
        }
    }
}
