/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IngestionEvent {
    TraceEvent1(Box<models::TraceEvent1>),
    ScoreEvent1(Box<models::ScoreEvent1>),
    CreateSpanEvent1(Box<models::CreateSpanEvent1>),
    UpdateSpanEvent1(Box<models::UpdateSpanEvent1>),
    CreateGenerationEvent1(Box<models::CreateGenerationEvent1>),
    UpdateGenerationEvent1(Box<models::UpdateGenerationEvent1>),
    CreateEventEvent1(Box<models::CreateEventEvent1>),
    SdkLogEvent1(Box<models::SdkLogEvent1>),
    CreateObservationEvent1(Box<models::CreateObservationEvent1>),
    UpdateObservationEvent1(Box<models::UpdateObservationEvent1>),
}

impl Default for IngestionEvent {
    fn default() -> Self {
        Self::TraceEvent1(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "trace-create")]
    TraceCreate,
    #[serde(rename = "score-create")]
    ScoreCreate,
    #[serde(rename = "span-create")]
    SpanCreate,
    #[serde(rename = "span-update")]
    SpanUpdate,
    #[serde(rename = "generation-create")]
    GenerationCreate,
    #[serde(rename = "generation-update")]
    GenerationUpdate,
    #[serde(rename = "event-create")]
    EventCreate,
    #[serde(rename = "sdk-log")]
    SdkLog,
    #[serde(rename = "observation-create")]
    ObservationCreate,
    #[serde(rename = "observation-update")]
    ObservationUpdate,
}

impl Default for Type {
    fn default() -> Type {
        Self::TraceCreate
    }
}
