/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LegacyMetricsResponse {
    /// The metrics data. Each item in the list contains the metric values and dimensions requested in the query. Format varies based on the query parameters. Histograms will return an array with [lower, upper, height] tuples.
    #[serde(rename = "data")]
    pub data: Vec<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "_deprecation", skip_serializing_if = "Option::is_none")]
    pub _deprecation: Option<Box<models::Deprecation>>,
}

impl LegacyMetricsResponse {
    pub fn new(
        data: Vec<std::collections::HashMap<String, serde_json::Value>>,
    ) -> LegacyMetricsResponse {
        LegacyMetricsResponse {
            data,
            _deprecation: None,
        }
    }
}
