/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegacyPromptVariableMapping : **Deprecated:** Connects one prompt variable to data from a legacy trace or dataset evaluation rule.  `langfuseObject` selects the object kind. `objectName` separately selects a named observation and is `null` for trace and dataset-item mappings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LegacyPromptVariableMapping {
    /// Explicitly marks this as a legacy mapping.
    #[serde(rename = "mappingType")]
    pub mapping_type: String,
    /// Prompt variable name without braces.
    #[serde(rename = "variable")]
    pub variable: String,
    #[serde(rename = "langfuseObject")]
    pub langfuse_object: models::LegacyEvaluationObject,
    /// Observation name to match, or `null` when `langfuseObject` is `trace` or `dataset_item`.
    #[serde(rename = "objectName", deserialize_with = "Option::deserialize")]
    pub object_name: Option<String>,
    /// Field selected from the legacy object.
    #[serde(rename = "source")]
    pub source: String,
    /// Optional JSONPath selector applied to the selected field.
    #[serde(
        rename = "jsonPath",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub json_path: Option<Option<String>>,
}

impl LegacyPromptVariableMapping {
    /// **Deprecated:** Connects one prompt variable to data from a legacy trace or dataset evaluation rule.  `langfuseObject` selects the object kind. `objectName` separately selects a named observation and is `null` for trace and dataset-item mappings.
    pub fn new(
        mapping_type: String,
        variable: String,
        langfuse_object: models::LegacyEvaluationObject,
        object_name: Option<String>,
        source: String,
    ) -> LegacyPromptVariableMapping {
        LegacyPromptVariableMapping {
            mapping_type,
            variable,
            langfuse_object,
            object_name,
            source,
            json_path: None,
        }
    }
}
