/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LegacyObservationsViews {
    #[serde(rename = "data")]
    pub data: Vec<models::ObservationsView>,
    #[serde(rename = "meta")]
    pub meta: Box<models::UtilsMetaResponse>,
    #[serde(rename = "_deprecation", skip_serializing_if = "Option::is_none")]
    pub _deprecation: Option<Box<models::Deprecation>>,
}

impl LegacyObservationsViews {
    pub fn new(
        data: Vec<models::ObservationsView>,
        meta: models::UtilsMetaResponse,
    ) -> LegacyObservationsViews {
        LegacyObservationsViews {
            data,
            meta: Box::new(meta),
            _deprecation: None,
        }
    }
}
