/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Model : Model definition used for transforming usage into USD cost and/or tokenization.  Models can have either simple flat pricing or tiered pricing: - Flat pricing: Single price per usage type (legacy, but still supported) - Tiered pricing: Multiple pricing tiers with conditional matching based on usage patterns  The pricing tiers approach is recommended for models with usage-based pricing variations. When using tiered pricing, the flat price fields (inputPrice, outputPrice, prices) are populated from the default tier for backward compatibility.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Model {
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the model definition. If multiple with the same name exist, they are applied in the following order: (1) custom over built-in, (2) newest according to startTime where model.startTime<observation.startTime
    #[serde(rename = "modelName")]
    pub model_name: String,
    /// Regex pattern which matches this model definition to generation.model. Useful in case of fine-tuned models. If you want to exact match, use `(?i)^modelname$`
    #[serde(rename = "matchPattern")]
    pub match_pattern: String,
    /// Apply only to generations which are newer than this ISO date.
    #[serde(
        rename = "startDate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub start_date: Option<Option<String>>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<models::ModelUsageUnit>,
    /// Deprecated. See 'prices' instead. Price (USD) per input unit
    #[serde(
        rename = "inputPrice",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_price: Option<Option<f64>>,
    /// Deprecated. See 'prices' instead. Price (USD) per output unit
    #[serde(
        rename = "outputPrice",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output_price: Option<Option<f64>>,
    /// Deprecated. See 'prices' instead. Price (USD) per total unit. Cannot be set if input or output price is set.
    #[serde(
        rename = "totalPrice",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_price: Option<Option<f64>>,
    /// Optional. Tokenizer to be applied to observations which match to this model. See docs for more details.
    #[serde(
        rename = "tokenizerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tokenizer_id: Option<Option<String>>,
    /// Optional. Configuration for the selected tokenizer. Needs to be JSON. See docs for more details.
    #[serde(
        rename = "tokenizerConfig",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tokenizer_config: Option<Option<serde_json::Value>>,
    #[serde(rename = "isLangfuseManaged")]
    pub is_langfuse_managed: bool,
    /// Timestamp when the model was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Deprecated. Use 'pricingTiers' instead for models with usage-based pricing variations.  This field shows prices by usage type from the default pricing tier. Maintained for backward compatibility. If the model uses tiered pricing, this field will be populated from the default tier's prices.
    #[serde(rename = "prices")]
    pub prices: std::collections::HashMap<String, models::ModelPrice>,
    /// Array of pricing tiers with conditional pricing based on usage thresholds.  Pricing tiers enable accurate cost tracking for models that charge different rates based on usage patterns (e.g., different rates for high-volume usage, large context windows, or cached tokens).  Each model must have exactly one default tier (isDefault=true, priority=0) that serves as a fallback. Additional conditional tiers can be defined with specific matching criteria.  If this array is empty, the model uses legacy flat pricing from the inputPrice/outputPrice/totalPrice fields.
    #[serde(rename = "pricingTiers")]
    pub pricing_tiers: Vec<models::PricingTier>,
}

impl Model {
    /// Model definition used for transforming usage into USD cost and/or tokenization.  Models can have either simple flat pricing or tiered pricing: - Flat pricing: Single price per usage type (legacy, but still supported) - Tiered pricing: Multiple pricing tiers with conditional matching based on usage patterns  The pricing tiers approach is recommended for models with usage-based pricing variations. When using tiered pricing, the flat price fields (inputPrice, outputPrice, prices) are populated from the default tier for backward compatibility.
    pub fn new(
        id: String,
        model_name: String,
        match_pattern: String,
        is_langfuse_managed: bool,
        created_at: String,
        prices: std::collections::HashMap<String, models::ModelPrice>,
        pricing_tiers: Vec<models::PricingTier>,
    ) -> Model {
        Model {
            id,
            model_name,
            match_pattern,
            start_date: None,
            unit: None,
            input_price: None,
            output_price: None,
            total_price: None,
            tokenizer_id: None,
            tokenizer_config: None,
            is_langfuse_managed,
            created_at,
            prices,
            pricing_tiers,
        }
    }
}
