/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ObservationsV2Response : Response containing observations with field-group-based filtering and cursor-based pagination.  The `data` array contains observation objects with only the requested field groups included. Use the `cursor` in `meta` to retrieve the next page of results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ObservationsV2Response {
    /// Array of observation objects. Fields included depend on the `fields` parameter in the request.
    #[serde(rename = "data")]
    pub data: Vec<models::ObservationV2>,
    #[serde(rename = "meta")]
    pub meta: Box<models::ObservationsV2Meta>,
}

impl ObservationsV2Response {
    /// Response containing observations with field-group-based filtering and cursor-based pagination.  The `data` array contains observation objects with only the requested field groups included. Use the `cursor` in `meta` to retrieve the next page of results.
    pub fn new(
        data: Vec<models::ObservationV2>,
        meta: models::ObservationsV2Meta,
    ) -> ObservationsV2Response {
        ObservationsV2Response {
            data,
            meta: Box::new(meta),
        }
    }
}
