/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OtelScopeSpan : Collection of spans from a single instrumentation scope
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct OtelScopeSpan {
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Box<models::OtelScope>>,
    /// Array of spans
    #[serde(
        rename = "spans",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub spans: Option<Option<Vec<models::OtelSpan>>>,
}

impl OtelScopeSpan {
    /// Collection of spans from a single instrumentation scope
    pub fn new() -> OtelScopeSpan {
        OtelScopeSpan {
            scope: None,
            spans: None,
        }
    }
}
