/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PatchMediaBody {
    /// The date and time when the media record was uploaded
    #[serde(rename = "uploadedAt")]
    pub uploaded_at: chrono::DateTime<chrono::FixedOffset>,
    /// The HTTP status code of the upload
    #[serde(rename = "uploadHttpStatus")]
    pub upload_http_status: i32,
    /// The HTTP error message of the upload
    #[serde(
        rename = "uploadHttpError",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub upload_http_error: Option<Option<String>>,
    /// The time in milliseconds it took to upload the media record
    #[serde(
        rename = "uploadTimeMs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub upload_time_ms: Option<Option<i32>>,
}

impl PatchMediaBody {
    pub fn new(
        uploaded_at: chrono::DateTime<chrono::FixedOffset>,
        upload_http_status: i32,
    ) -> PatchMediaBody {
        PatchMediaBody {
            uploaded_at,
            upload_http_status,
            upload_http_error: None,
            upload_time_ms: None,
        }
    }
}
