/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PricingTierUsageCondition : Condition that sums usage details whose keys match a regex.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PricingTierUsageCondition {
    /// Regex pattern matched against usage detail keys.
    #[serde(rename = "usageDetailPattern")]
    pub usage_detail_pattern: String,
    #[serde(rename = "operator")]
    pub operator: models::PricingTierOperator,
    /// Numeric threshold for the summed matching usage values.
    #[serde(rename = "value")]
    pub value: f64,
    /// Whether the usage-detail regex is case-sensitive.
    #[serde(rename = "caseSensitive")]
    pub case_sensitive: bool,
}

impl PricingTierUsageCondition {
    /// Condition that sums usage details whose keys match a regex.
    pub fn new(
        usage_detail_pattern: String,
        operator: models::PricingTierOperator,
        value: f64,
        case_sensitive: bool,
    ) -> PricingTierUsageCondition {
        PricingTierUsageCondition {
            usage_detail_pattern,
            operator,
            value,
            case_sensitive,
        }
    }
}
