/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PricingTierUsageCondition : Condition that sums usage details whose keys match a regex.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PricingTierUsageCondition {
    /// Regex pattern matched against usage detail keys.
    #[serde(rename = "usageDetailPattern")]
    pub usage_detail_pattern: String,
    #[serde(rename = "operator")]
    pub operator: models::PricingTierOperator,
    /// Numeric threshold for the summed matching usage values.
    #[serde(rename = "value")]
    pub value: f64,
    /// Whether the usage-detail regex is case-sensitive.
    #[serde(rename = "caseSensitive")]
    pub case_sensitive: bool,
}

impl PricingTierUsageCondition {
    /// Condition that sums usage details whose keys match a regex.
    pub fn new(
        usage_detail_pattern: String,
        operator: models::PricingTierOperator,
        value: f64,
        case_sensitive: bool,
    ) -> PricingTierUsageCondition {
        PricingTierUsageCondition {
            usage_detail_pattern,
            operator,
            value,
            case_sensitive,
        }
    }
}
