/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PricingTierAttributeCondition : Condition that matches any configured value for a top-level observation attribute.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PricingTierAttributeCondition {
    #[serde(rename = "source")]
    pub source: models::PricingTierAttributeSource,
    /// Exact top-level attribute key.
    #[serde(rename = "key")]
    pub key: String,
    /// Membership operator.
    #[serde(rename = "operator")]
    pub operator: String,
    /// Accepted string attribute values. At least one value is required.
    #[serde(rename = "values")]
    pub values: Vec<String>,
}

impl PricingTierAttributeCondition {
    /// Condition that matches any configured value for a top-level observation attribute.
    pub fn new(
        source: models::PricingTierAttributeSource,
        key: String,
        operator: String,
        values: Vec<String>,
    ) -> PricingTierAttributeCondition {
        PricingTierAttributeCondition {
            source,
            key,
            operator,
            values,
        }
    }
}
