/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PricingTierConditionInput : Condition input for matching a pricing tier.
/// Condition input for matching a pricing tier.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PricingTierConditionInput {
    PricingTierUsageConditionInput(Box<models::PricingTierUsageConditionInput>),
    PricingTierAttributeCondition(Box<models::PricingTierAttributeCondition>),
}

impl Default for PricingTierConditionInput {
    fn default() -> Self {
        Self::PricingTierUsageConditionInput(Default::default())
    }
}
