/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PublicEvaluatorNumericScore {
    /// Optional instructions for deriving the reasoning returned with the score.
    #[serde(
        rename = "scoreReasoningInstructions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub score_reasoning_instructions: Option<Option<String>>,
    /// Optional instructions for deriving the score value.
    #[serde(
        rename = "scoreValueInstructions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub score_value_instructions: Option<Option<String>>,
    /// Numeric score output.
    #[serde(rename = "dataType")]
    pub data_type: String,
    /// Optional inclusive minimum value.
    #[serde(
        rename = "minValue",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_value: Option<Option<f64>>,
    /// Optional inclusive maximum value.
    #[serde(
        rename = "maxValue",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_value: Option<Option<f64>>,
}

impl PublicEvaluatorNumericScore {
    pub fn new(data_type: String) -> PublicEvaluatorNumericScore {
        PublicEvaluatorNumericScore {
            score_reasoning_instructions: None,
            score_value_instructions: None,
            data_type,
            min_value: None,
            max_value: None,
        }
    }
}
