/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicEvaluatorOutputDefinition : Flat evaluator output definition returned by the public API.  This response always includes `dataType` and never includes an internal output-definition `version`. Optional empty descriptions from legacy definitions are omitted.
/// Flat evaluator output definition returned by the public API.  This response always includes `dataType` and never includes an internal output-definition `version`. Optional empty descriptions from legacy definitions are omitted.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicEvaluatorOutputDefinition {
    PublicEvaluatorNumericScore1(Box<models::PublicEvaluatorNumericScore1>),
    PublicEvaluatorBooleanScore1(Box<models::PublicEvaluatorBooleanScore1>),
    PublicEvaluatorCategoricalScore1(Box<models::PublicEvaluatorCategoricalScore1>),
}

impl Default for PublicEvaluatorOutputDefinition {
    fn default() -> Self {
        Self::PublicEvaluatorNumericScore1(Default::default())
    }
}
