/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicApiError : Standard error response for the stable evaluators and evaluation-rules API.  Use the HTTP status for the broad failure class and `code` for programmatic handling. `details` is included when field-level validation or retry information is available.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PublicApiError {
    /// Human-readable description of the failure.
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "code")]
    pub code: models::PublicApiErrorCode,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Box<models::PublicApiErrorDetails>>,
}

impl PublicApiError {
    /// Standard error response for the stable evaluators and evaluation-rules API.  Use the HTTP status for the broad failure class and `code` for programmatic handling. `details` is included when field-level validation or retry information is available.
    pub fn new(message: String, code: models::PublicApiErrorCode) -> PublicApiError {
        PublicApiError {
            message,
            code,
            details: None,
        }
    }
}
