/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicApiErrorDetails : Optional structured context for validation and rate-limit errors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PublicApiErrorDetails {
    /// Validation issues for an invalid request body or query.
    #[serde(
        rename = "issues",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issues: Option<Option<Vec<models::PublicApiValidationIssue>>>,
    /// Number of seconds to wait before retrying a rate-limited request.
    #[serde(
        rename = "retryAfterSeconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub retry_after_seconds: Option<Option<i32>>,
    /// Rate-limit request allowance.
    #[serde(
        rename = "limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit: Option<Option<i32>>,
    /// Remaining requests in the current rate-limit window.
    #[serde(
        rename = "remaining",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub remaining: Option<Option<i32>>,
    /// Time when the current rate-limit window resets.
    #[serde(
        rename = "resetAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reset_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl PublicApiErrorDetails {
    /// Optional structured context for validation and rate-limit errors.
    pub fn new() -> PublicApiErrorDetails {
        PublicApiErrorDetails {
            issues: None,
            retry_after_seconds: None,
            limit: None,
            remaining: None,
            reset_at: None,
        }
    }
}
