/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicApiErrorCode : Stable machine-readable error code returned by the evaluators and evaluation-rules API.
/// Stable machine-readable error code returned by the evaluators and evaluation-rules API.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PublicApiErrorCode {
    #[serde(rename = "authentication_failed")]
    AuthenticationFailed,
    #[serde(rename = "access_denied")]
    AccessDenied,
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "invalid_query")]
    InvalidQuery,
    #[serde(rename = "invalid_body")]
    InvalidBody,
    #[serde(rename = "resource_not_found")]
    ResourceNotFound,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "method_not_allowed")]
    MethodNotAllowed,
    #[serde(rename = "internal_error")]
    InternalError,
}

impl std::fmt::Display for PublicApiErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuthenticationFailed => write!(f, "authentication_failed"),
            Self::AccessDenied => write!(f, "access_denied"),
            Self::InvalidRequest => write!(f, "invalid_request"),
            Self::InvalidQuery => write!(f, "invalid_query"),
            Self::InvalidBody => write!(f, "invalid_body"),
            Self::ResourceNotFound => write!(f, "resource_not_found"),
            Self::Conflict => write!(f, "conflict"),
            Self::RateLimited => write!(f, "rate_limited"),
            Self::MethodNotAllowed => write!(f, "method_not_allowed"),
            Self::InternalError => write!(f, "internal_error"),
        }
    }
}

impl Default for PublicApiErrorCode {
    fn default() -> PublicApiErrorCode {
        Self::AuthenticationFailed
    }
}
