/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ScimUser {
    #[serde(rename = "schemas")]
    pub schemas: Vec<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "name")]
    pub name: Box<models::ScimName>,
    #[serde(rename = "emails")]
    pub emails: Vec<models::ScimEmail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::UserMeta>,
}

impl ScimUser {
    pub fn new(
        schemas: Vec<String>,
        id: String,
        user_name: String,
        name: models::ScimName,
        emails: Vec<models::ScimEmail>,
        meta: models::UserMeta,
    ) -> ScimUser {
        ScimUser {
            schemas,
            id,
            user_name,
            name: Box::new(name),
            emails,
            meta: Box::new(meta),
        }
    }
}
