/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScoreV1 {
    NumericScoreV11(Box<models::NumericScoreV11>),
    CategoricalScoreV11(Box<models::CategoricalScoreV11>),
    BooleanScoreV11(Box<models::BooleanScoreV11>),
    TextScoreV11(Box<models::TextScoreV11>),
}

impl Default for ScoreV1 {
    fn default() -> Self {
        Self::NumericScoreV11(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "TEXT")]
    Text,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Text
    }
}
