/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScoreV3 {
    NumericScoreV31(Box<models::NumericScoreV31>),
    BooleanScoreV31(Box<models::BooleanScoreV31>),
    CategoricalScoreV31(Box<models::CategoricalScoreV31>),
    TextScoreV31(Box<models::TextScoreV31>),
    CorrectionScoreV31(Box<models::CorrectionScoreV31>),
}

impl Default for ScoreV3 {
    fn default() -> Self {
        Self::NumericScoreV31(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "CORRECTION")]
    Correction,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Correction
    }
}
