/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ScoreV3OneOf1 {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: models::ScoreSource,
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
    /// The environment from which this score originated.
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Optional comment attached to the score. Present when \"details\" is included in the fields parameter.
    #[serde(
        rename = "comment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub comment: Option<Option<String>>,
    /// The score config ID, if this score was created from a config. Present when \"details\" is included in the fields parameter.
    #[serde(
        rename = "configId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config_id: Option<Option<String>>,
    /// Arbitrary metadata attached to the score. Present when \"details\" is included in the fields parameter.
    #[serde(
        rename = "metadata",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// The user who created this score, if available. Present when \"annotation\" is included in the fields parameter.
    #[serde(
        rename = "authorUserId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub author_user_id: Option<Option<String>>,
    /// The annotation queue this score belongs to, if any. Present when \"annotation\" is included in the fields parameter.
    #[serde(
        rename = "queueId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub queue_id: Option<Option<String>>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Box<models::ScoreSubjectV3>>,
    /// The boolean value of the score.
    #[serde(rename = "value")]
    pub value: bool,
    #[serde(rename = "dataType")]
    pub data_type: DataType,
}

impl ScoreV3OneOf1 {
    pub fn new(
        id: String,
        project_id: String,
        name: String,
        source: models::ScoreSource,
        timestamp: chrono::DateTime<chrono::FixedOffset>,
        environment: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        value: bool,
        data_type: DataType,
    ) -> ScoreV3OneOf1 {
        ScoreV3OneOf1 {
            id,
            project_id,
            name,
            source,
            timestamp,
            environment,
            created_at,
            updated_at,
            comment: None,
            config_id: None,
            metadata: None,
            author_user_id: None,
            queue_id: None,
            subject: None,
            value,
            data_type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "BOOLEAN")]
    Boolean,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Boolean
    }
}
