/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScoreSubjectV3 : A reference to the entity this score is attached to. Discriminated by \"kind\" — one of trace, observation, session, or experiment.
/// A reference to the entity this score is attached to. Discriminated by \"kind\" — one of trace, observation, session, or experiment.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScoreSubjectV3 {
    ScoreSubjectTraceV31(Box<models::ScoreSubjectTraceV31>),
    ScoreSubjectObservationV31(Box<models::ScoreSubjectObservationV31>),
    ScoreSubjectSessionV31(Box<models::ScoreSubjectSessionV31>),
    ScoreSubjectExperimentV31(Box<models::ScoreSubjectExperimentV31>),
}

impl Default for ScoreSubjectV3 {
    fn default() -> Self {
        Self::ScoreSubjectTraceV31(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "experiment")]
    Experiment,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Experiment
    }
}
