/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Score {
    NumericScore1(Box<models::NumericScore1>),
    CategoricalScore1(Box<models::CategoricalScore1>),
    BooleanScore1(Box<models::BooleanScore1>),
    CorrectionScore1(Box<models::CorrectionScore1>),
    TextScore1(Box<models::TextScore1>),
}

impl Default for Score {
    fn default() -> Self {
        Self::NumericScore1(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "TEXT")]
    Text,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Text
    }
}
