/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Score {
    ScoreOneOf(Box<models::ScoreOneOf>),
    ScoreOneOf1(Box<models::ScoreOneOf1>),
    ScoreOneOf2(Box<models::ScoreOneOf2>),
    ScoreOneOf3(Box<models::ScoreOneOf3>),
}

impl Default for Score {
    fn default() -> Self {
        Self::ScoreOneOf(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "CORRECTION")]
    Correction,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Correction
    }
}
