/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScoreSubjectV3 : A reference to the entity this score is attached to. Discriminated by \"kind\" — one of trace, observation, session, or experiment.
/// A reference to the entity this score is attached to. Discriminated by \"kind\" — one of trace, observation, session, or experiment.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScoreSubjectV3 {
    ScoreSubjectTraceV31(Box<models::ScoreSubjectTraceV31>),
    ScoreSubjectObservationV31(Box<models::ScoreSubjectObservationV31>),
    ScoreSubjectSessionV31(Box<models::ScoreSubjectSessionV31>),
    ScoreSubjectExperimentV31(Box<models::ScoreSubjectExperimentV31>),
}

impl Default for ScoreSubjectV3 {
    fn default() -> Self {
        Self::ScoreSubjectTraceV31(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "experiment")]
    Experiment,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Experiment
    }
}
