/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ScoreSubjectV3OneOf {
    /// The trace ID.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
}

impl ScoreSubjectV3OneOf {
    pub fn new(id: String, kind: Kind) -> ScoreSubjectV3OneOf {
        ScoreSubjectV3OneOf { id, kind }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "trace")]
    Trace,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Trace
    }
}
