/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct SubmitFeedbackRequest {
    #[serde(rename = "targetType")]
    pub target_type: models::FeedbackTargetType,
    /// The specific instance within targetType: the skill name, MCP tool name, CLI command, API endpoint path, or docs page path (e.g. 'queryMetrics', '/docs/mcp'). An identifier, not a sentence. Must be between 1 and 200 characters.
    #[serde(rename = "target")]
    pub target: String,
    /// Concise feedback text approved by the user. Must be between 1 and 3000 characters.
    #[serde(rename = "feedback")]
    pub feedback: String,
    /// Optional user-approved goal or use case they were trying to achieve. Must be between 1 and 1500 characters when provided. Do not include secrets, customer data, trace payloads, or broad unrelated context.
    #[serde(
        rename = "goal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub goal: Option<Option<String>>,
    /// Optional HTTP(S) reference URL. Langfuse stores it as text for triage and does not fetch it.
    #[serde(
        rename = "referenceUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reference_url: Option<Option<String>>,
}

impl SubmitFeedbackRequest {
    pub fn new(
        target_type: models::FeedbackTargetType,
        target: String,
        feedback: String,
    ) -> SubmitFeedbackRequest {
        SubmitFeedbackRequest {
            target_type,
            target,
            feedback,
            goal: None,
            reference_url: None,
        }
    }
}
