/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableCreateEvaluatorRequestOneOf1 {
    /// Evaluator name within the authenticated project.
    #[serde(rename = "name")]
    pub name: String,
    /// Code executed for each matched observation.
    #[serde(rename = "sourceCode")]
    pub source_code: String,
    #[serde(rename = "sourceCodeLanguage")]
    pub source_code_language: models::UnstableCodeEvaluatorSourceCodeLanguage,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl UnstableCreateEvaluatorRequestOneOf1 {
    pub fn new(
        name: String,
        source_code: String,
        source_code_language: models::UnstableCodeEvaluatorSourceCodeLanguage,
        r#type: Type,
    ) -> UnstableCreateEvaluatorRequestOneOf1 {
        UnstableCreateEvaluatorRequestOneOf1 {
            name,
            source_code,
            source_code_language,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "code")]
    Code,
}

impl Default for Type {
    fn default() -> Type {
        Self::Code
    }
}
