/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableDashboardWidgetFilter : A dashboard widget filter in Langfuse filter-state shape.  Filter shapes depend on `type`, for example string filters use a string `value`, option filters use a list of strings, and object filters include `key`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableDashboardWidgetFilter {
    #[serde(rename = "column")]
    pub column: String,
    #[serde(rename = "operator")]
    pub operator: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(
        rename = "value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub key: Option<Option<String>>,
}

impl UnstableDashboardWidgetFilter {
    /// A dashboard widget filter in Langfuse filter-state shape.  Filter shapes depend on `type`, for example string filters use a string `value`, option filters use a list of strings, and object filters include `key`.
    pub fn new(column: String, operator: String, r#type: String) -> UnstableDashboardWidgetFilter {
        UnstableDashboardWidgetFilter {
            column,
            operator,
            r#type,
            value: None,
            key: None,
        }
    }
}
