/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstablePublicApiErrorDetails : Optional structured context attached to an error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePublicApiErrorDetails {
    #[serde(
        rename = "issues",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issues: Option<Option<Vec<models::UnstablePublicApiValidationIssue>>>,
    #[serde(
        rename = "field",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub field: Option<Option<String>>,
    #[serde(
        rename = "column",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub column: Option<Option<String>>,
    #[serde(
        rename = "invalidValues",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub invalid_values: Option<Option<Vec<String>>>,
    #[serde(
        rename = "allowedValues",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_values: Option<Option<Vec<String>>>,
    #[serde(
        rename = "value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Option<String>>,
    #[serde(
        rename = "retryAfterSeconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub retry_after_seconds: Option<Option<i32>>,
    #[serde(
        rename = "limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit: Option<Option<i32>>,
    #[serde(
        rename = "remaining",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub remaining: Option<Option<i32>>,
    #[serde(
        rename = "resetAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reset_at: Option<Option<String>>,
}

impl UnstablePublicApiErrorDetails {
    /// Optional structured context attached to an error.
    pub fn new() -> UnstablePublicApiErrorDetails {
        UnstablePublicApiErrorDetails {
            issues: None,
            field: None,
            column: None,
            invalid_values: None,
            allowed_values: None,
            value: None,
            retry_after_seconds: None,
            limit: None,
            remaining: None,
            reset_at: None,
        }
    }
}
