/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstablePublicApiError : Standard error envelope for the unstable evaluators API.  Response handling guidance: - Use the HTTP status code for the broad class of failure. - Use `code` for precise branching in SDKs, CLIs, or agents. - Inspect `details` for field-level validation context such as invalid filter values, malformed JSONPath expressions, or missing variable mappings. - Retry only after fixing the specific issue described by `code` and `details`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePublicApiError {
    /// Human-readable description of the failure.
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "code")]
    pub code: models::UnstablePublicApiErrorCode,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Box<models::UnstablePublicApiErrorDetails>>,
}

impl UnstablePublicApiError {
    /// Standard error envelope for the unstable evaluators API.  Response handling guidance: - Use the HTTP status code for the broad class of failure. - Use `code` for precise branching in SDKs, CLIs, or agents. - Inspect `details` for field-level validation context such as invalid filter values, malformed JSONPath expressions, or missing variable mappings. - Retry only after fixing the specific issue described by `code` and `details`.
    pub fn new(
        message: String,
        code: models::UnstablePublicApiErrorCode,
    ) -> UnstablePublicApiError {
        UnstablePublicApiError {
            message,
            code,
            details: None,
        }
    }
}
