/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstablePublicApiErrorCode : Machine-readable error code returned by the unstable evaluators API.  SDKs, CLIs, and agents should branch on `code` rather than parsing the human-readable `message`. The HTTP status still indicates the broad error class, while `code` gives the specific failure reason.
/// Machine-readable error code returned by the unstable evaluators API.  SDKs, CLIs, and agents should branch on `code` rather than parsing the human-readable `message`. The HTTP status still indicates the broad error class, while `code` gives the specific failure reason.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstablePublicApiErrorCode {
    #[serde(rename = "authentication_failed")]
    AuthenticationFailed,
    #[serde(rename = "access_denied")]
    AccessDenied,
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "invalid_query")]
    InvalidQuery,
    #[serde(rename = "invalid_body")]
    InvalidBody,
    #[serde(rename = "invalid_filter_value")]
    InvalidFilterValue,
    #[serde(rename = "invalid_json_path")]
    InvalidJsonPath,
    #[serde(rename = "invalid_variable_mapping")]
    InvalidVariableMapping,
    #[serde(rename = "missing_variable_mapping")]
    MissingVariableMapping,
    #[serde(rename = "duplicate_variable_mapping")]
    DuplicateVariableMapping,
    #[serde(rename = "resource_not_found")]
    ResourceNotFound,
    #[serde(rename = "name_conflict")]
    NameConflict,
    #[serde(rename = "evaluator_preflight_failed")]
    EvaluatorPreflightFailed,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "unprocessable_content")]
    UnprocessableContent,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "method_not_allowed")]
    MethodNotAllowed,
    #[serde(rename = "internal_error")]
    InternalError,
}

impl std::fmt::Display for UnstablePublicApiErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuthenticationFailed => write!(f, "authentication_failed"),
            Self::AccessDenied => write!(f, "access_denied"),
            Self::InvalidRequest => write!(f, "invalid_request"),
            Self::InvalidQuery => write!(f, "invalid_query"),
            Self::InvalidBody => write!(f, "invalid_body"),
            Self::InvalidFilterValue => write!(f, "invalid_filter_value"),
            Self::InvalidJsonPath => write!(f, "invalid_json_path"),
            Self::InvalidVariableMapping => write!(f, "invalid_variable_mapping"),
            Self::MissingVariableMapping => write!(f, "missing_variable_mapping"),
            Self::DuplicateVariableMapping => write!(f, "duplicate_variable_mapping"),
            Self::ResourceNotFound => write!(f, "resource_not_found"),
            Self::NameConflict => write!(f, "name_conflict"),
            Self::EvaluatorPreflightFailed => write!(f, "evaluator_preflight_failed"),
            Self::Conflict => write!(f, "conflict"),
            Self::UnprocessableContent => write!(f, "unprocessable_content"),
            Self::RateLimited => write!(f, "rate_limited"),
            Self::MethodNotAllowed => write!(f, "method_not_allowed"),
            Self::InternalError => write!(f, "internal_error"),
        }
    }
}

impl Default for UnstablePublicApiErrorCode {
    fn default() -> UnstablePublicApiErrorCode {
        Self::AuthenticationFailed
    }
}
