/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableSkillVersion {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "createdBy")]
    pub created_by: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "frontmatter", deserialize_with = "Option::deserialize")]
    pub frontmatter: Option<serde_json::Value>,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "labels")]
    pub labels: Vec<String>,
    #[serde(rename = "commitMessage", deserialize_with = "Option::deserialize")]
    pub commit_message: Option<String>,
    #[serde(rename = "files")]
    pub files: Vec<models::UnstableSkillFile>,
}

impl UnstableSkillVersion {
    pub fn new(
        id: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        project_id: String,
        created_by: String,
        name: String,
        description: String,
        frontmatter: Option<serde_json::Value>,
        version: i32,
        tags: Vec<String>,
        labels: Vec<String>,
        commit_message: Option<String>,
        files: Vec<models::UnstableSkillFile>,
    ) -> UnstableSkillVersion {
        UnstableSkillVersion {
            id,
            created_at,
            updated_at,
            project_id,
            created_by,
            name,
            description,
            frontmatter,
            version,
            tags,
            labels,
            commit_message,
            files,
        }
    }
}
