/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableCreatePresetPlacement {
    /// Server-generated when omitted.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    #[serde(rename = "presetId")]
    pub preset_id: String,
    /// Grid column (12-column grid). Defaults to `0`.
    #[serde(
        rename = "x",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub x: Option<Option<i32>>,
    /// Grid row. Defaults to the first row below all existing tiles.
    #[serde(
        rename = "y",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub y: Option<Option<i32>>,
    /// Width in grid columns. Defaults to `6`.
    #[serde(
        rename = "width",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub width: Option<Option<i32>>,
    /// Height in grid rows. Defaults to `6`.
    #[serde(
        rename = "height",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub height: Option<Option<i32>>,
}

impl UnstableCreatePresetPlacement {
    pub fn new(preset_id: String) -> UnstableCreatePresetPlacement {
        UnstableCreatePresetPlacement {
            id: None,
            preset_id,
            x: None,
            y: None,
            width: None,
            height: None,
        }
    }
}
