/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableSkillMeta {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "latestVersion")]
    pub latest_version: i32,
    #[serde(rename = "latestVersionCreatedAt")]
    pub latest_version_created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "latestVersionLastUpdatedAt")]
    pub latest_version_last_updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Version assigned the production label, or null when no version is assigned.
    #[serde(rename = "productionVersion", deserialize_with = "Option::deserialize")]
    pub production_version: Option<i32>,
}

impl UnstableSkillMeta {
    pub fn new(
        name: String,
        description: String,
        tags: Vec<String>,
        latest_version: i32,
        latest_version_created_at: chrono::DateTime<chrono::FixedOffset>,
        latest_version_last_updated_at: chrono::DateTime<chrono::FixedOffset>,
        production_version: Option<i32>,
    ) -> UnstableSkillMeta {
        UnstableSkillMeta {
            name,
            description,
            tags,
            latest_version,
            latest_version_created_at,
            latest_version_last_updated_at,
            production_version,
        }
    }
}
