/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePublicCategoricalEvaluatorOutputDefinition {
    #[serde(rename = "dataType")]
    pub data_type: DataType,
    #[serde(rename = "reasoning")]
    pub reasoning: Box<models::UnstableEvaluatorOutputFieldDefinition>,
    #[serde(rename = "score")]
    pub score: Box<models::UnstablePublicCategoricalEvaluatorOutputScoreDefinition>,
}

impl UnstablePublicCategoricalEvaluatorOutputDefinition {
    pub fn new(
        data_type: DataType,
        reasoning: models::UnstableEvaluatorOutputFieldDefinition,
        score: models::UnstablePublicCategoricalEvaluatorOutputScoreDefinition,
    ) -> UnstablePublicCategoricalEvaluatorOutputDefinition {
        UnstablePublicCategoricalEvaluatorOutputDefinition {
            data_type,
            reasoning: Box::new(reasoning),
            score: Box::new(score),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "CATEGORICAL")]
    Categorical,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Categorical
    }
}
