/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableDashboardWidgetChartType {
    #[serde(rename = "LINE_TIME_SERIES")]
    LineTimeSeries,
    #[serde(rename = "AREA_TIME_SERIES")]
    AreaTimeSeries,
    #[serde(rename = "BAR_TIME_SERIES")]
    BarTimeSeries,
    #[serde(rename = "HORIZONTAL_BAR")]
    HorizontalBar,
    #[serde(rename = "VERTICAL_BAR")]
    VerticalBar,
    #[serde(rename = "PIE")]
    Pie,
    #[serde(rename = "NUMBER")]
    Number,
    #[serde(rename = "HISTOGRAM")]
    Histogram,
    #[serde(rename = "PIVOT_TABLE")]
    PivotTable,
}

impl std::fmt::Display for UnstableDashboardWidgetChartType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LineTimeSeries => write!(f, "LINE_TIME_SERIES"),
            Self::AreaTimeSeries => write!(f, "AREA_TIME_SERIES"),
            Self::BarTimeSeries => write!(f, "BAR_TIME_SERIES"),
            Self::HorizontalBar => write!(f, "HORIZONTAL_BAR"),
            Self::VerticalBar => write!(f, "VERTICAL_BAR"),
            Self::Pie => write!(f, "PIE"),
            Self::Number => write!(f, "NUMBER"),
            Self::Histogram => write!(f, "HISTOGRAM"),
            Self::PivotTable => write!(f, "PIVOT_TABLE"),
        }
    }
}

impl Default for UnstableDashboardWidgetChartType {
    fn default() -> UnstableDashboardWidgetChartType {
        Self::LineTimeSeries
    }
}
