/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePresetPlacement {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "presetId")]
    pub preset_id: String,
    #[serde(rename = "x")]
    pub x: i32,
    #[serde(rename = "y")]
    pub y: i32,
    #[serde(rename = "width")]
    pub width: i32,
    #[serde(rename = "height")]
    pub height: i32,
}

impl UnstablePresetPlacement {
    pub fn new(
        id: String,
        preset_id: String,
        x: i32,
        y: i32,
        width: i32,
        height: i32,
    ) -> UnstablePresetPlacement {
        UnstablePresetPlacement {
            id,
            preset_id,
            x,
            y,
            width,
            height,
        }
    }
}
