/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableEvaluatorOutputDataType : Structured score type returned by an evaluator.  This controls the type of score value Langfuse stores for evaluation results: - `NUMERIC`: a numeric score such as `0.82` - `BOOLEAN`: a boolean score such as `true` - `CATEGORICAL`: one or more category labels from a fixed list
/// Structured score type returned by an evaluator.  This controls the type of score value Langfuse stores for evaluation results: - `NUMERIC`: a numeric score such as `0.82` - `BOOLEAN`: a boolean score such as `true` - `CATEGORICAL`: one or more category labels from a fixed list
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableEvaluatorOutputDataType {
    #[serde(rename = "NUMERIC")]
    Numeric,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "CATEGORICAL")]
    Categorical,
}

impl std::fmt::Display for UnstableEvaluatorOutputDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Numeric => write!(f, "NUMERIC"),
            Self::Boolean => write!(f, "BOOLEAN"),
            Self::Categorical => write!(f, "CATEGORICAL"),
        }
    }
}

impl Default for UnstableEvaluatorOutputDataType {
    fn default() -> UnstableEvaluatorOutputDataType {
        Self::Numeric
    }
}
