/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableDashboardDefinition {
    #[serde(rename = "widgets")]
    pub widgets: Vec<models::UnstableDashboardPlacement>,
}

impl UnstableDashboardDefinition {
    pub fn new(widgets: Vec<models::UnstableDashboardPlacement>) -> UnstableDashboardDefinition {
        UnstableDashboardDefinition { widgets }
    }
}
