/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableCodeEvaluatorSourceCodeLanguage : Code evaluator runtime language.
/// Code evaluator runtime language.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableCodeEvaluatorSourceCodeLanguage {
    #[serde(rename = "PYTHON")]
    Python,
    #[serde(rename = "TYPESCRIPT")]
    Typescript,
}

impl std::fmt::Display for UnstableCodeEvaluatorSourceCodeLanguage {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Python => write!(f, "PYTHON"),
            Self::Typescript => write!(f, "TYPESCRIPT"),
        }
    }
}

impl Default for UnstableCodeEvaluatorSourceCodeLanguage {
    fn default() -> UnstableCodeEvaluatorSourceCodeLanguage {
        Self::Python
    }
}
