/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableDashboardPlacement : A tile on the dashboard's 12-column grid. `x`/`y` are the tile's top-left cell (0-based; `y` grows downward), `width`/`height` its size in cells. The UI default tile is 6x6 (half width). Overlapping tiles are not rejected; prefer appending below existing tiles (or omit the position on create to let the server do it).
/// A tile on the dashboard's 12-column grid. `x`/`y` are the tile's top-left cell (0-based; `y` grows downward), `width`/`height` its size in cells. The UI default tile is 6x6 (half width). Overlapping tiles are not rejected; prefer appending below existing tiles (or omit the position on create to let the server do it).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableDashboardPlacement {
    UnstableWidgetPlacement(Box<models::UnstableWidgetPlacement>),
    UnstablePresetPlacement(Box<models::UnstablePresetPlacement>),
}

impl Default for UnstableDashboardPlacement {
    fn default() -> Self {
        Self::UnstableWidgetPlacement(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "widget")]
    Widget,
    #[serde(rename = "preset")]
    Preset,
}

impl Default for Type {
    fn default() -> Type {
        Self::Widget
    }
}
