/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableDashboard {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "definition")]
    pub definition: Box<models::UnstableDashboardDefinition>,
    /// Dashboard-level filters applied to all widgets on the dashboard.
    #[serde(rename = "filters")]
    pub filters: Vec<models::UnstableDashboardWidgetFilter>,
}

impl UnstableDashboard {
    pub fn new(
        id: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        name: String,
        description: String,
        definition: models::UnstableDashboardDefinition,
        filters: Vec<models::UnstableDashboardWidgetFilter>,
    ) -> UnstableDashboard {
        UnstableDashboard {
            id,
            created_at,
            updated_at,
            name,
            description,
            definition: Box::new(definition),
            filters,
        }
    }
}
