/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableEvaluatorType : The evaluator engine type.  The unstable public API currently supports only LLM-as-a-judge evaluators.
/// The evaluator engine type.  The unstable public API currently supports only LLM-as-a-judge evaluators.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableEvaluatorType {
    #[serde(rename = "llm_as_judge")]
    LlmAsJudge,
}

impl std::fmt::Display for UnstableEvaluatorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LlmAsJudge => write!(f, "llm_as_judge"),
        }
    }
}

impl Default for UnstableEvaluatorType {
    fn default() -> UnstableEvaluatorType {
        Self::LlmAsJudge
    }
}
