/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableDashboardWidgetViewWithLegacy : Widget data view. Responses may include the legacy `traces` value for widgets created before this API existed.
/// Widget data view. Responses may include the legacy `traces` value for widgets created before this API existed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableDashboardWidgetViewWithLegacy {
    #[serde(rename = "observations")]
    Observations,
    #[serde(rename = "scores-numeric")]
    ScoresNumeric,
    #[serde(rename = "scores-boolean")]
    ScoresBoolean,
    #[serde(rename = "scores-categorical")]
    ScoresCategorical,
    #[serde(rename = "traces")]
    Traces,
}

impl std::fmt::Display for UnstableDashboardWidgetViewWithLegacy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Observations => write!(f, "observations"),
            Self::ScoresNumeric => write!(f, "scores-numeric"),
            Self::ScoresBoolean => write!(f, "scores-boolean"),
            Self::ScoresCategorical => write!(f, "scores-categorical"),
            Self::Traces => write!(f, "traces"),
        }
    }
}

impl Default for UnstableDashboardWidgetViewWithLegacy {
    fn default() -> UnstableDashboardWidgetViewWithLegacy {
        Self::Observations
    }
}
