/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableDashboardList {
    #[serde(rename = "data")]
    pub data: Vec<models::UnstableDashboard>,
    #[serde(rename = "meta")]
    pub meta: Box<models::UtilsMetaResponse>,
}

impl UnstableDashboardList {
    pub fn new(
        data: Vec<models::UnstableDashboard>,
        meta: models::UtilsMetaResponse,
    ) -> UnstableDashboardList {
        UnstableDashboardList {
            data,
            meta: Box::new(meta),
        }
    }
}
