/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableEvaluatorOutputDefinition : Structured output definition to send when creating an evaluator.  Agent guidance: - `dataType` is required. - Do not send `version`; that is an internal storage detail and is not part of the public request contract. - For `NUMERIC` and `BOOLEAN`, provide `reasoning.description` and `score.description`. - For `NUMERIC`, `score.minValue` and `score.maxValue` optionally define inclusive bounds. If both are set, `minValue` must not exceed `maxValue`. - For `CATEGORICAL`, also provide `score.categories` and `score.shouldAllowMultipleMatches`.
/// Structured output definition to send when creating an evaluator.  Agent guidance: - `dataType` is required. - Do not send `version`; that is an internal storage detail and is not part of the public request contract. - For `NUMERIC` and `BOOLEAN`, provide `reasoning.description` and `score.description`. - For `NUMERIC`, `score.minValue` and `score.maxValue` optionally define inclusive bounds. If both are set, `minValue` must not exceed `maxValue`. - For `CATEGORICAL`, also provide `score.categories` and `score.shouldAllowMultipleMatches`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnstableEvaluatorOutputDefinition {
    UnstablePublicNumericEvaluatorOutputDefinition(
        Box<models::UnstablePublicNumericEvaluatorOutputDefinition>,
    ),
    UnstablePublicBooleanEvaluatorOutputDefinition(
        Box<models::UnstablePublicBooleanEvaluatorOutputDefinition>,
    ),
    UnstablePublicCategoricalEvaluatorOutputDefinition(
        Box<models::UnstablePublicCategoricalEvaluatorOutputDefinition>,
    ),
}

impl Default for UnstableEvaluatorOutputDefinition {
    fn default() -> Self {
        Self::UnstablePublicNumericEvaluatorOutputDefinition(Default::default())
    }
}
