/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableCreateDashboardWidgetRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// Defaults to an empty string.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "view")]
    pub view: models::UnstableDashboardWidgetView,
    #[serde(rename = "dimensions")]
    pub dimensions: Vec<models::UnstableDashboardWidgetDimension>,
    #[serde(rename = "metrics")]
    pub metrics: Vec<models::UnstableDashboardWidgetMetric>,
    #[serde(rename = "filters")]
    pub filters: Vec<models::UnstableDashboardWidgetFilter>,
    #[serde(rename = "chartType")]
    pub chart_type: models::UnstableDashboardWidgetChartType,
    #[serde(rename = "chartConfig", skip_serializing_if = "Option::is_none")]
    pub chart_config: Option<Box<models::UnstableDashboardWidgetChartConfigInput>>,
}

impl UnstableCreateDashboardWidgetRequest {
    pub fn new(
        name: String,
        view: models::UnstableDashboardWidgetView,
        dimensions: Vec<models::UnstableDashboardWidgetDimension>,
        metrics: Vec<models::UnstableDashboardWidgetMetric>,
        filters: Vec<models::UnstableDashboardWidgetFilter>,
        chart_type: models::UnstableDashboardWidgetChartType,
    ) -> UnstableCreateDashboardWidgetRequest {
        UnstableCreateDashboardWidgetRequest {
            name,
            description: None,
            view,
            dimensions,
            metrics,
            filters,
            chart_type,
            chart_config: None,
        }
    }
}
