/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableUpdateDashboardWidgetRequest {
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "view", skip_serializing_if = "Option::is_none")]
    pub view: Option<models::UnstableDashboardWidgetView>,
    #[serde(
        rename = "dimensions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub dimensions: Option<Option<Vec<models::UnstableDashboardWidgetDimension>>>,
    #[serde(
        rename = "metrics",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metrics: Option<Option<Vec<models::UnstableDashboardWidgetMetric>>>,
    #[serde(
        rename = "filters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub filters: Option<Option<Vec<models::UnstableDashboardWidgetFilter>>>,
    #[serde(rename = "chartType", skip_serializing_if = "Option::is_none")]
    pub chart_type: Option<models::UnstableDashboardWidgetChartType>,
    #[serde(rename = "chartConfig", skip_serializing_if = "Option::is_none")]
    pub chart_config: Option<Box<models::UnstableDashboardWidgetChartConfigInput>>,
}

impl UnstableUpdateDashboardWidgetRequest {
    pub fn new() -> UnstableUpdateDashboardWidgetRequest {
        UnstableUpdateDashboardWidgetRequest {
            name: None,
            description: None,
            view: None,
            dimensions: None,
            metrics: None,
            filters: None,
            chart_type: None,
            chart_config: None,
        }
    }
}
