/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePublicNumericEvaluatorOutputScoreDefinition {
    #[serde(rename = "description")]
    pub description: String,
    /// Inclusive minimum value for numeric evaluator scores.
    #[serde(
        rename = "minValue",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_value: Option<Option<f64>>,
    /// Inclusive maximum value for numeric evaluator scores.
    #[serde(
        rename = "maxValue",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_value: Option<Option<f64>>,
}

impl UnstablePublicNumericEvaluatorOutputScoreDefinition {
    pub fn new(description: String) -> UnstablePublicNumericEvaluatorOutputScoreDefinition {
        UnstablePublicNumericEvaluatorOutputScoreDefinition {
            description,
            min_value: None,
            max_value: None,
        }
    }
}
