/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstableCreateDashboardWidgetRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "view")]
    pub view: models::UnstableDashboardWidgetView,
    #[serde(rename = "dimensions")]
    pub dimensions: Vec<models::UnstableDashboardWidgetDimension>,
    #[serde(rename = "metrics")]
    pub metrics: Vec<models::UnstableDashboardWidgetMetric>,
    #[serde(rename = "filters")]
    pub filters: Vec<models::UnstableDashboardWidgetFilter>,
    #[serde(rename = "chartType")]
    pub chart_type: models::UnstableDashboardWidgetChartType,
    #[serde(rename = "chartConfig")]
    pub chart_config: Box<models::UnstableDashboardWidgetChartConfig>,
    #[serde(
        rename = "minVersion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_version: Option<Option<i32>>,
}

impl UnstableCreateDashboardWidgetRequest {
    pub fn new(
        name: String,
        description: String,
        view: models::UnstableDashboardWidgetView,
        dimensions: Vec<models::UnstableDashboardWidgetDimension>,
        metrics: Vec<models::UnstableDashboardWidgetMetric>,
        filters: Vec<models::UnstableDashboardWidgetFilter>,
        chart_type: models::UnstableDashboardWidgetChartType,
        chart_config: models::UnstableDashboardWidgetChartConfig,
    ) -> UnstableCreateDashboardWidgetRequest {
        UnstableCreateDashboardWidgetRequest {
            name,
            description,
            view,
            dimensions,
            metrics,
            filters,
            chart_type,
            chart_config: Box::new(chart_config),
            min_version: None,
        }
    }
}
