/*
 * server
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableDashboardWidgetView {
    #[serde(rename = "observations")]
    Observations,
    #[serde(rename = "scores-numeric")]
    ScoresNumeric,
    #[serde(rename = "scores-categorical")]
    ScoresCategorical,
}

impl std::fmt::Display for UnstableDashboardWidgetView {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Observations => write!(f, "observations"),
            Self::ScoresNumeric => write!(f, "scores-numeric"),
            Self::ScoresCategorical => write!(f, "scores-categorical"),
        }
    }
}

impl Default for UnstableDashboardWidgetView {
    fn default() -> UnstableDashboardWidgetView {
        Self::Observations
    }
}
