/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePublicCategoricalEvaluatorOutputScoreDefinition {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
    #[serde(rename = "shouldAllowMultipleMatches")]
    pub should_allow_multiple_matches: bool,
}

impl UnstablePublicCategoricalEvaluatorOutputScoreDefinition {
    pub fn new(
        description: String,
        categories: Vec<String>,
        should_allow_multiple_matches: bool,
    ) -> UnstablePublicCategoricalEvaluatorOutputScoreDefinition {
        UnstablePublicCategoricalEvaluatorOutputScoreDefinition {
            description,
            categories,
            should_allow_multiple_matches,
        }
    }
}
