/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnstableEvaluatorScope : Where an evaluator comes from.  - `project`: created in your project - `managed`: provided by Langfuse
/// Where an evaluator comes from.  - `project`: created in your project - `managed`: provided by Langfuse
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnstableEvaluatorScope {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "managed")]
    Managed,
}

impl std::fmt::Display for UnstableEvaluatorScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Project => write!(f, "project"),
            Self::Managed => write!(f, "managed"),
        }
    }
}

impl Default for UnstableEvaluatorScope {
    fn default() -> UnstableEvaluatorScope {
        Self::Project
    }
}
