/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UnstablePublicCategoricalEvaluatorOutputDefinition {
    #[serde(rename = "dataType")]
    pub data_type: models::UnstableEvaluatorOutputDataType,
    #[serde(rename = "reasoning")]
    pub reasoning: Box<models::UnstableEvaluatorOutputFieldDefinition>,
    #[serde(rename = "score")]
    pub score: Box<models::UnstablePublicCategoricalEvaluatorOutputScoreDefinition>,
}

impl UnstablePublicCategoricalEvaluatorOutputDefinition {
    pub fn new(
        data_type: models::UnstableEvaluatorOutputDataType,
        reasoning: models::UnstableEvaluatorOutputFieldDefinition,
        score: models::UnstablePublicCategoricalEvaluatorOutputScoreDefinition,
    ) -> UnstablePublicCategoricalEvaluatorOutputDefinition {
        UnstablePublicCategoricalEvaluatorOutputDefinition {
            data_type,
            reasoning: Box::new(reasoning),
            score: Box::new(score),
        }
    }
}
