/*
 * server
 *
 * ## Real-time data  The only real-time path to get tracing data is to ingest via OpenTelemetry (`POST /api/public/otel/v1/traces`) and retrieve via Observations API v2 (`GET /api/public/v2/observations`) and Metrics API v2 (`GET /api/public/v2/metrics`). Other public API write and read endpoints can delay data by about 10 minutes. Direct OpenTelemetry exporters must send the `x-langfuse-ingestion-version: 4` header; current Python and JS SDKs already do. See the [Public API docs](https://langfuse.com/docs/api-and-data-platform/features/public-api) and [real-time ingestion](https://langfuse.com/integrations/native/opentelemetry.md#real-time-ingestion).  ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Self-hosted deployments: interactive API reference at `/api/docs` and OpenAPI spec at `/api/openapi.yaml`
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct UtilsMetaResponse {
    /// current page number
    #[serde(rename = "page")]
    pub page: i32,
    /// number of items per page
    #[serde(rename = "limit")]
    pub limit: i32,
    /// number of total items given the current filters/selection (if any)
    #[serde(rename = "totalItems")]
    pub total_items: i32,
    /// number of total pages given the current limit
    #[serde(rename = "totalPages")]
    pub total_pages: i32,
}

impl UtilsMetaResponse {
    pub fn new(page: i32, limit: i32, total_items: i32, total_pages: i32) -> UtilsMetaResponse {
        UtilsMetaResponse {
            page,
            limit,
            total_items,
            total_pages,
        }
    }
}
