name: CI

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref/SHA to checkout'
        required: false
        type: string
      persist_credentials:
        description: 'Whether to persist checkout credentials'
        required: false
        type: boolean
        default: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, 1.82.0]
    steps:
      - name: Checkout repository (default)
        if: inputs.ref == ''
        uses: actions/checkout@v4
        with:
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Checkout repository (ref)
        if: inputs.ref != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Build documentation
        run: cargo doc --no-deps --all-features

      - name: Run tests
        run: cargo test --verbose

      - name: Check formatting
        if: matrix.rust == 'stable'
        run: cargo fmt --all -- --check

      - name: Run clippy
        if: matrix.rust == 'stable'
        run: cargo clippy --all-targets --all-features -- -D warnings
