name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    # Skip normal CI for bot/*, renovate/* and release-plz-* PRs; bot workflow handles it
    if: github.event_name != 'pull_request' || (!startsWith(github.event.pull_request.head.ref, 'bot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && !startsWith(github.event.pull_request.head.ref, 'release-plz-'))
    uses: ./.github/workflows/ci-common.yml
