name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write

env:
  CARGO_TERM_COLOR: always

jobs:
  # Verify the generated code compiles
  build:
    name: Build (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, 1.82.0]  # 1.82.0 is our MSRV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Build
        run: cargo build --verbose
        
      - name: Build documentation
        run: cargo doc --no-deps --all-features
        
      - name: Run clippy (strict)
        if: matrix.rust == 'stable'
        run: cargo clippy --all-targets --all-features -- -D warnings
        
      - name: Check formatting
        if: matrix.rust == 'stable'
        run: cargo fmt --all -- --check

  # Security audit - quick check for PRs
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Cargo.lock for audit
        run: cargo generate-lockfile
        
      - name: Run cargo audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
