name: Debug PR Events

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, edited]

jobs:
  debug:
    name: Debug PR Event
    runs-on: ubuntu-latest
    
    steps:
      - name: Log all PR event details
        uses: actions/github-script@v7
        with:
          script: |
            console.log('=== PR EVENT DEBUG ===');
            console.log('Event:', context.eventName);
            console.log('Action:', context.payload.action);
            console.log('PR number:', context.payload.pull_request.number);
            console.log('PR title:', context.payload.pull_request.title);
            console.log('Labels:', context.payload.pull_request.labels.map(l => l.name));
            console.log('Has skip-ci:', context.payload.pull_request.labels.some(l => l.name === 'skip-ci'));
            
            if (context.payload.action === 'labeled') {
              console.log('New label added:', context.payload.label.name);
            }
            
            if (context.payload.action === 'unlabeled') {
              console.log('Label removed:', context.payload.label.name);
            }
            
            console.log('Created by:', context.payload.pull_request.user.login);
            console.log('Head ref:', context.payload.pull_request.head.ref);
            console.log('=== END DEBUG ===');