name: Dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  udeps:
    # Skip normal deps check for automated/* PRs; automated workflow handles it
    # Use github.head_ref which is empty on push and set on PRs
    if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'automated/')
    uses: ./.github/workflows/deps-common.yml
