name: Dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  udeps:
    # Skip normal deps check for bot-created client update and release-plz PRs; bot workflow handles it
    if: github.event_name != 'pull_request' || (github.event.pull_request.head.ref != 'auto/update-generated-client' && !startsWith(github.event.pull_request.head.ref, 'release-plz-'))
    uses: ./.github/workflows/deps-common.yml
