name: Dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  udeps:
    # Skip normal deps check for automated/* PRs; automated workflow handles it
    if: github.event_name != 'pull_request' || !startsWith(github.event.pull_request.head.ref, 'automated/')
    uses: ./.github/workflows/deps-common.yml
