name: Dependencies

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref/SHA to checkout'
        required: false
        type: string
      persist_credentials:
        description: 'Whether to persist checkout credentials'
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  udeps:
    name: Check Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (default)
        if: inputs.ref == ''
        uses: actions/checkout@v4
        with:
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Checkout repository (ref)
        if: inputs.ref != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo-udeps
        uses: actions/cache@v4
        id: cache-udeps
        with:
          path: ~/.cargo/bin/cargo-udeps
          key: cargo-udeps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-udeps
        if: steps.cache-udeps.outputs.cache-hit != 'true'
        run: cargo install cargo-udeps --locked

      - name: Run cargo-udeps
        run: cargo +nightly udeps --all-targets --all-features
