name: Dependencies (Bot PRs)

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read

jobs:
  udeps:
    # Only run for PRs opened by github-actions bot
    if: github.actor == 'github-actions[bot]'
    uses: ./.github/workflows/deps-common.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      persist_credentials: false
