name: Dependencies (Bot PRs)

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read

jobs:
  udeps:
    # Only run for bot-created PRs for nightly client or release-plz
    if: startsWith(github.event.pull_request.user.login, 'app/') && (github.event.pull_request.head.ref == 'auto/update-generated-client' || startsWith(github.event.pull_request.head.ref, 'release-plz-'))
    uses: ./.github/workflows/deps-common.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      persist_credentials: false
