name: Dependencies (Bot PRs)

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read

jobs:
  udeps:
    # Run for nightly client branch or release-plz branches
    if: github.event.pull_request.head.ref == 'auto/update-generated-client' || startsWith(github.event.pull_request.head.ref, 'release-plz-')
    uses: ./.github/workflows/deps-common.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      persist_credentials: false
