name: Dependencies (Bot PRs)

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read

jobs:
  udeps:
    # Run for bot/ prefix or release-plz branches
    if: startsWith(github.event.pull_request.head.ref, 'bot/') || startsWith(github.event.pull_request.head.ref, 'release-plz-') || startsWith(github.event.pull_request.head.ref, 'renovate/')
    uses: ./.github/workflows/deps-common.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      persist_credentials: false
