name: Generate Client

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install OpenAPI Generator
        run: |
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli version

      - name: Generate client
        run: |
          ./scripts/generate-openapi-client.sh

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update generated client from latest OpenAPI spec'
          title: 'chore: update generated client from latest OpenAPI spec'
          body: |
            ## 🤖 Auto-generated Update
            
            This PR updates the generated client based on the latest OpenAPI specification from Langfuse.
            
            ### Changes
            - Updated generated code in `src/` from latest OpenAPI spec
            - Applied automatic formatting
            
            ### Pre-merge Checklist
            - [ ] Review the changes to ensure they look reasonable
            - [ ] Check that the build passes
            - [ ] Verify no breaking changes for downstream consumers
            
            ---
            *This PR was automatically created by the nightly generation workflow.*
          branch: auto/update-generated-client
          delete-branch: true
          labels: |
            dependencies
            automated

  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // This step ensures the workflow stays active even during periods of inactivity
            // GitHub disables scheduled workflows after 60 days of repository inactivity
            
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflow_id = 'generate-client.yml';
            
            // Get the workflow
            const workflow = await github.rest.actions.getWorkflow({
              owner,
              repo,
              workflow_id
            });
            
            console.log(`Workflow ${workflow.data.name} is ${workflow.data.state}`);
            
            // If the workflow is disabled, re-enable it
            if (workflow.data.state === 'disabled_inactivity') {
              await github.rest.actions.enableWorkflow({
                owner,
                repo,
                workflow_id
              });
              console.log('Workflow re-enabled');
            }
            
            // Log the last run to show activity
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id,
              per_page: 1
            });
            
            if (runs.data.workflow_runs.length > 0) {
              const lastRun = runs.data.workflow_runs[0];
              console.log(`Last run: ${lastRun.created_at} - Status: ${lastRun.status}`);
            }