name: Release-plz

# These permissions are needed for release-plz to work
permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    # Explicitly set permissions at job level too
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      # Prefer short-lived GitHub App token if available; fall back to GH_BOT_TOKEN
      - name: Create GitHub App token (optional)
        id: app-token
        if: ${{ secrets.BOT_APP_ID != '' && secrets.BOT_PRIVATE_KEY != '' }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
        
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          # Use a PAT/GitHub App token so PR events trigger workflows
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || secrets.GH_BOT_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
