name: Security (Bot PRs)

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  security:
    if: github.actor == 'github-actions[bot]'
    uses: ./.github/workflows/security-common.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      persist_credentials: false
    secrets: inherit
