name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight UTC

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  security:
    # Skip normal security checks for bot/*, renovate/* and release-plz-* PRs; bot workflow handles it
    if: github.event_name != 'pull_request' || (!startsWith(github.event.pull_request.head.ref, 'bot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && !startsWith(github.event.pull_request.head.ref, 'release-plz-'))
    uses: ./.github/workflows/security-common.yml
    secrets: inherit
