name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight UTC

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  security:
    # Skip normal security checks for automated/* PRs; automated workflow handles it
    # Use github.head_ref which is empty on push and set on PRs
    if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'automated/')
    uses: ./.github/workflows/security-common.yml
    secrets: inherit
