name: Security (Bot PRs)

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  security:
    if: (startsWith(github.event.pull_request.user.login, 'app/') || github.event.pull_request.user.login == 'github-actions[bot]') && github.event.pull_request.head.ref == 'auto/update-generated-client'
    uses: ./.github/workflows/security-common.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      persist_credentials: false
    secrets: inherit
