name: Security

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref/SHA to checkout'
        required: false
        type: string
      persist_credentials:
        description: 'Whether to persist checkout credentials'
        required: false
        type: boolean
        default: true
    secrets:
      GITHUB_TOKEN:
        required: true
      GITLEAKS_LICENSE:
        required: false

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (default)
        if: inputs.ref == ''
        uses: actions/checkout@v4
        with:
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Checkout repository (ref)
        if: inputs.ref != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Generate Cargo.lock for audit
        run: cargo generate-lockfile

      - name: Run cargo audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  trufflehog:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history, default)
        if: inputs.ref == ''
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Checkout repository (full history, ref)
        if: inputs.ref != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          persist-credentials: ${{ inputs.persist_credentials }}

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
          extra_args: --only-verified
